# Generated by Django 4.2.7 on 2023-11-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="accuracy",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="has_taken_software_engineering_course",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.AddField(
            model_name="customuser",
            name="has_taken_software_course",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="department",
            field=models.CharField(
                choices=[
                    ("cse", "CSE"),
                    ("eee", "EEE"),
                    ("mpe", "MPE"),
                    ("btm", "BTM"),
                ],
                default="default_department_value",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
