# Generated by Django 4.2.7 on 2023-11-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_review_student_user_annotation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="ground_truth_annotation",
            new_name="label",
        ),
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
