# Generated by Django 4.2.7 on 2023-12-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_annotation_label_annotation_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentannotation",
            name="label",
            field=models.IntegerField(default=1),
        ),
    ]
