# Generated by Django 4.2.7 on 2023-11-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_ground_truth_annotation_review_label_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="label",
            new_name="ground_truth_annotation",
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
