# Generated by Django 4.2.7 on 2023-12-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_studentannotation_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="unannotatedreview",
            name="annotation_count",
            field=models.IntegerField(default=0),
        ),
    ]
