# Generated by Django 4.2.7 on 2023-12-21 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_studentannotation_student1_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentannotation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="studentannotation",
            name="annotation",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentannotation",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentannotation",
            unique_together={("review", "student")},
        ),
        migrations.RemoveField(
            model_name="studentannotation",
            name="student1_id",
        ),
        migrations.RemoveField(
            model_name="studentannotation",
            name="student1annotation",
        ),
        migrations.RemoveField(
            model_name="studentannotation",
            name="student2_id",
        ),
        migrations.RemoveField(
            model_name="studentannotation",
            name="student2annotation",
        ),
        migrations.RemoveField(
            model_name="studentannotation",
            name="student3_id",
        ),
        migrations.RemoveField(
            model_name="studentannotation",
            name="student3annotation",
        ),
    ]
