# Generated by Django 4.2.7 on 2023-12-21 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_studentannotation_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentannotation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="studentannotation",
            name="student1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student1_annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentannotation",
            name="student1annotation",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentannotation",
            name="student2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student2_annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentannotation",
            name="student2annotation",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentannotation",
            name="student3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student3_annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentannotation",
            name="student3annotation",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="studentannotation",
            name="annotation",
        ),
        migrations.RemoveField(
            model_name="studentannotation",
            name="student",
        ),
    ]
