# Generated by Django 4.2.7 on 2023-12-22 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_studentannotation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentannotation",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentannotation",
            name="value",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="studentannotation",
            unique_together={("review", "student")},
        ),
        migrations.RemoveField(
            model_name="studentannotation",
            name="student1",
        ),
        migrations.RemoveField(
            model_name="studentannotation",
            name="student1annotation",
        ),
        migrations.RemoveField(
            model_name="studentannotation",
            name="student2",
        ),
        migrations.RemoveField(
            model_name="studentannotation",
            name="student2annotation",
        ),
        migrations.RemoveField(
            model_name="studentannotation",
            name="student3",
        ),
        migrations.RemoveField(
            model_name="studentannotation",
            name="student3annotation",
        ),
    ]
