# Generated by Django 4.2.7 on 2023-12-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_studentannotation_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="department",
            field=models.CharField(
                choices=[
                    ("cse", "CSE"),
                    ("eee", "EEE"),
                    ("mpe", "MPE"),
                    ("btm", "BTM"),
                ],
                max_length=100,
            ),
        ),
    ]
