# Generated by Django 4.2.7 on 2024-01-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_customuser_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="software_related_courses",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="customuser",
            name="working_experience",
            field=models.IntegerField(default=0),
        ),
    ]
