# Generated by Django 4.2.7 on 2024-01-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_customuser_age_customuser_software_related_courses_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="has_taken_software_course",
        ),
    ]
