# Generated by Django 4.2.7 on 2024-02-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_annotatedreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotatedreview",
            name="content",
            field=models.TextField(default=""),
        ),
    ]
