# Generated by Django 4.2.7 on 2024-02-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_annotatedreview_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="unannotatedreview",
            name="is_fully_annotated",
            field=models.BooleanField(default=False),
        ),
    ]
