# Generated by Django 4.2.7 on 2024-05-09 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_unannotatedreview_is_fully_annotated"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentproject",
            name="description",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentproject",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="studentproject",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
