# Generated by Django 4.2.7 on 2024-06-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_studentproject_uploaded_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentproject",
            name="annotators_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="studentproject",
            name="labels",
            field=models.TextField(
                default="", help_text="Comma-separated list of labels"
            ),
        ),
        migrations.AddField(
            model_name="studentproject",
            name="output_format",
            field=models.CharField(
                choices=[("csv", "CSV"), ("json", "JSON")],
                default="csv",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="studentproject",
            name="review_column",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="studentproject",
            name="sections_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="studentproject",
            name="unique_link",
            field=models.CharField(unique=True, blank=True, max_length=32),
        ),
    ]
