# Generated by Django 4.2.7 on 2024-06-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_populate_unique_link"),
        ("myapp", "0024_populate_unique_links"),
    ]

    operations = []
