# Generated by Django 4.2.7 on 2024-06-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0026_populate_unique_links_correctly"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentproject",
            name="labeled_file",
            field=models.FileField(
                blank=True, null=True, upload_to="labeled_files/%Y/%m/%d/"
            ),
        ),
    ]
