# Generated by Django 4.2.7 on 2024-06-02 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0027_studentproject_labeled_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentproject",
            name="uploaded_file",
            field=models.FileField(
                upload_to="uploads/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv"]
                    )
                ],
            ),
        ),
    ]
